In [57]:
import pandas as pd
import os
from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
import string
# nltk.download()

In [58]:
def cleanArticle(file2read):

    stop_words = set(stopwords.words('english') + list(string.punctuation)) # decleare extra words and punctioations

    article = '' # declare the returning variable
    customExtras = ["\n", "'", "“", "”", "'", "`", "-", "[", "]", "»"] # declare extra chars of article which are not included in the previous packages 
    
    def listToString(s): #function that converts arr of strings into one string (used later)
        str1 = " "
        return (str1.join(s))


    for i in customExtras: # remove extra chars in article
        file2read = file2read.replace(i, " ")

    
    word_tokens= word_tokenize(file2read.lower()) #converts article into array of words
    # print(word_tokens)


    filtered_file2read =[] #empty array of clean words

    for w in word_tokens: # check if word from article is the extra , if not assign the word in the clean words array
        if w not in stop_words and w.isalpha() == True:
            filtered_file2read.append(w)

    # print(filtered_file2read)


    article = listToString(filtered_file2read)
    # print(article)
    

    return article

In [59]:
#change directory to technology training
os.chdir("articles/technology/training")


articles = []
genres = []
item = 1


#open training technology articles
while(item <= 100):
    file2read = open("TrTechnologyArticle" + str(item) +
                     ".txt", 'r').read()
    file2read = cleanArticle(file2read) #cleanarticle was declared before
    articles.append(file2read)
    genres.append("technology")
    item += 1

item = 1

#change directory to sports training
os.chdir("../../sports/training")

#open training sports articles
while(item <= 100):
    file2read = open("TrSportsArticle" + str(item) +
                     ".txt", 'r').read().replace("\n", "")
    file2read = cleanArticle(file2read)
    articles.append(file2read)
    genres.append("sports")
    item += 1 


#declare dictionary that becomes dataframe
trainingData = {'article':  articles,
                'genre': genres
                }

# print(articles[2])

os.chdir("../../../")






trainingData = pd.DataFrame(trainingData)
trainingData

                                               article       genre
0    apple today released ios ipados minor bug fix ...  technology
1    expected apple rolling ios iphone users update...  technology
2    apple wednesday released ios ipados bug fixes ...  technology
3    iphone models emergency sos via satellite feat...  technology
4    apple released ios ipados iphone ipad download...  technology
..                                                 ...         ...
195  smu topped houston saturday highest scoring re...      sports
196  smu quarterback tanner mordecai tossed nine to...      sports
197  smu houston offenses unstoppable saturday ap w...      sports
198  evanston ryan day reasonable explanation took ...      sports
199  subscription supports investigative reporting ...      sports

[200 rows x 2 columns]

In [60]:

os.chdir("articles/technology/testing")
temp = os.getcwd()


articles = []
genres = []
item = 101


os.getcwd


while(item >= 101 and item <=200):
    file2read = open("TeTechnologyArticle" + str(item) +
                     ".txt", 'r').read()
    file2read = cleanArticle(file2read)
    articles.append(file2read)
    genres.append("technology")
    item += 1

item = 101

os.chdir("../../sports/testing")

while(item >= 101 and item <=200):
    file2read = open("TeSportsArticle" + str(item) +
                     ".txt", 'r').read()
    file2read = cleanArticle(file2read)
    articles.append(file2read)
    genres.append("sports")
    item += 1


testingData = {'article':  articles,
                'genre': genres
                }

# print(articles[2])

os.chdir("../../../")


testingData = pd.DataFrame(testingData)
testingData

                                               article       genre
0    cbs essentials created independently cbs news ...  technology
1    update wed nov gmt appearing pegi website last...  technology
2    publisher devolver digital developer daniel mu...  technology
3    finally allowing posting last year instagram c...  technology
4    since instagram introduced website let users a...  technology
..                                                 ...         ...
195  houston human nature amped maybe game extra bu...      sports
196  let get philadelphia eagles links predicting n...      sports
197  jesse mendez breakout performance first colleg...      sports
198  twitter instagram facebook order ohio state ti...      sports
199  ccole mattin sam janicki michigan crowned four...      sports

[200 rows x 2 columns]

In [61]:
#assign `label`` to training and testing dataframes if sports then label = 1  if not label = 0
# we assign label for naive beyes
trainingData['label'] = trainingData['genre'].apply(lambda x: 0 if x=="sports" else 1) 
testingData['label'] = testingData['genre'].apply(lambda x: 0 if x=="sports" else 1)
 
# trainingData
trainingData

                                               article       genre  label
0    apple today released ios ipados minor bug fix ...  technology      1
1    expected apple rolling ios iphone users update...  technology      1
2    apple wednesday released ios ipados bug fixes ...  technology      1
3    iphone models emergency sos via satellite feat...  technology      1
4    apple released ios ipados iphone ipad download...  technology      1
..                                                 ...         ...    ...
195  smu topped houston saturday highest scoring re...      sports      0
196  smu quarterback tanner mordecai tossed nine to...      sports      0
197  smu houston offenses unstoppable saturday ap w...      sports      0
198  evanston ryan day reasonable explanation took ...      sports      0
199  subscription supports investigative reporting ...      sports      0

[200 rows x 3 columns]

In [62]:
#dataframe manipulation 
df = testingData #declare new
df = testingData.append(trainingData, ignore_index=True)#  append declarted dataframe with training data
df

C:\Users\Luka\AppData\Local\Temp\ipykernel_18644\876022514.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = testingData.append(trainingData, ignore_index=True)#  append declarted dataframe with training data

                                               article       genre  label
0    cbs essentials created independently cbs news ...  technology      1
1    update wed nov gmt appearing pegi website last...  technology      1
2    publisher devolver digital developer daniel mu...  technology      1
3    finally allowing posting last year instagram c...  technology      1
4    since instagram introduced website let users a...  technology      1
..                                                 ...         ...    ...
395  smu topped houston saturday highest scoring re...      sports      0
396  smu quarterback tanner mordecai tossed nine to...      sports      0
397  smu houston offenses unstoppable saturday ap w...      sports      0
398  evanston ryan day reasonable explanation took ...      sports      0
399  subscription supports investigative reporting ...      sports      0

[400 rows x 3 columns]

In [63]:
from sklearn.model_selection import train_test_split
taining_x, X_test, y_train, y_test = train_test_split(df['article'], df['label'], random_state=1) #X - articles fortesting and training y- labels for testing and training
y_train

82     1
367    0
179    0
27     1
89     1
      ..
255    1
72     1
396    0
235    1
37     1
Name: label, Length: 300, dtype: int64

In [64]:
cv = CountVectorizer(strip_accents="ascii") # tokenizes the documents andconverts it to matrix
taining_x_cv = cv.fit_transform(taining_x) #Learn the vocabulary dictionary and return document-term matrix.
X_test_cv = cv.transform(X_test) #Transform documents to document-term matrix. according to the previous fit_transform() standard
# print(taining_x_cv)
print(X_test_cv)

  (0, 495)	1
  (0, 721)	1
  (0, 883)	1
  (0, 1263)	2
  (0, 2880)	1
  (0, 3218)	1
  (0, 3647)	1
  (0, 3962)	1
  (0, 3999)	1
  (0, 4090)	1
  (0, 4341)	1
  (0, 4527)	1
  (0, 4866)	2
  (0, 4962)	1
  (0, 5225)	1
  (0, 6449)	1
  (0, 6587)	2
  (0, 6978)	1
  (0, 7027)	1
  (0, 8058)	1
  (0, 8078)	2
  (0, 8108)	1
  (0, 8890)	2
  (0, 8906)	1
  (0, 9077)	1
  :	:
  (99, 12112)	1
  (99, 12126)	1
  (99, 12150)	1
  (99, 12212)	1
  (99, 12283)	1
  (99, 12407)	1
  (99, 12427)	1
  (99, 12513)	1
  (99, 12514)	1
  (99, 12526)	1
  (99, 12592)	1
  (99, 12594)	2
  (99, 12628)	6
  (99, 12672)	8
  (99, 12738)	6
  (99, 12745)	1
  (99, 12938)	1
  (99, 12982)	4
  (99, 13001)	1
  (99, 13034)	2
  (99, 13076)	1
  (99, 13275)	4
  (99, 13293)	1
  (99, 13295)	3
  (99, 13326)	1

In [65]:
# ta = len(taining_x_cv.toarray())
word_freq_df = pd.DataFrame(taining_x_cv.toarray(), columns=cv.get_feature_names())
top_words_df = pd.DataFrame(word_freq_df.sum()).sort_values(0, ascending=False)
# print(word_freq_df["apple"][130:200])
# i = 0
# while i < 200:
#     if word_freq_df["aac"][i] !=0:
#         print(word_freq_df["aac"][i])
print(word_freq_df)
print(top_words_df)
# print(ta)

     aaa  aac  aaep  aapl  aaron  aatrox  abandoned  abanikanda  abbreviated  \
0      0    0     0     0      0       0          0           0            0
1      0    0     0     0      0       0          0           0            0
2      0    0     0     0      0       0          0           0            0
3      0    0     0     0      0       0          0           0            0
4      0    0     0     0      0       0          0           0            0
..   ...  ...   ...   ...    ...     ...        ...         ...          ...
295    0    0     0     0      0       0          0           0            0
296    0    0     0     0      0       0          0           0            0
297    0    0     0     0      0       0          0           0            0
298    0    0     0     0      0       0          0           0            0
299    0    0     0     0      0       0          0           0            0

     abc  ...  zion  zip  zlabs  zone  zoom  zooming  zork  zuber  zuckerberg  \
0      0  ...     0    0      0     0     0        0     0      0           0
1      0  ...     0    0      0     0     0        0     0      0           0
2      0  ...     0    0      0     0     0        0     0      0           0
3      0  ...     0    0      0     0     0        0     0      0           0
4      0  ...     0    0      0     0     0        0     0      0           0
..   ...  ...   ...  ...    ...   ...   ...      ...   ...    ...         ...
295    0  ...     0    0      0     0     0        0     0      0           0
296    0  ...     0    0      0     0     0        0     0      0           0
297    0  ...     0    0      0     0     0        0     0      0           0
298    0  ...     0    0      0     0     0        0     0      0           0
299    0  ...     0    0      0     0     0        0     0      0           0

     zwormz
0         0
1         0
2         0
3         0
4         0
..      ...
295       0
296       0
297       0
298       0
299       0

[300 rows x 13336 columns]
             0
game       916
one        651
first      637
new        536
said       494
...        ...
producing    1
produces     1
producer     1
produce      1
zwormz       1

[13336 rows x 1 columns]

C:\Users\Luka\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [66]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB() # declare naive beyes model
naive_bayes.fit(taining_x_cv, y_train) #trian naive beyes model
predictions = naive_bayes.predict(X_test_cv) #predict
ara = naive_bayes.predict(X_test_cv[0])
print(ara)
predictions

[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [67]:
#display accuracy Percision and Recall
from sklearn.metrics import accuracy_score, precision_score, recall_score
accuracy ='Accuracy score: ' + str(accuracy_score(y_test, predictions))
recallScore = 'Recall score: '+ str(recall_score(y_test, predictions))
percisionScore = 'Precision score: ' + str(precision_score(y_test, predictions))

print(accuracy)
print(recallScore)
print(percisionScore)

Accuracy score: 1.0
Recall score: 1.0
Precision score: 1.0

In [68]:
preds = [] #array later column which will contain predictions
for i in range(len(X_test)): #loop length = total amound of documents
    if predictions[i] == 1: #if predicion of that document is 1 which means it's a technology append preds with tech else append woth sports
        preds.append('technology')
    else:
        preds.append('sports')
predictedData = pd.DataFrame({'actual label': list(y_test), 'prediction': preds, 'article':list(X_test)}) #init new dataframe with three columns actual label and so on
predictedData.replace(to_replace=0, value='sports', inplace=True) #replace 0s in table with sports
predictedData.replace(to_replace=1, value='technology', inplace=True) #replace 1s in table with tech

predictedData

   actual label  prediction                                            article
0        sports      sports  evanston ryan day reasonable explanation took ...
1        sports      sports  melbourne nov reuters south africa blame disap...
2        sports      sports  week stressing important win future notre dame...
3        sports      sports  michigan state shook turmoil filled week snapp...
4        sports      sports  setting nba dfs lineups sites like draftkings ...
..          ...         ...                                                ...
95       sports      sports  philadelphia phillies chances capturing first ...
96   technology  technology  publisher devolver digital developer ahr ech a...
97   technology  technology  vr headset kill user die game founder claims d...
98   technology  technology  days supercomputing kicks intel introduced ope...
99       sports      sports  increased role versus hornets team ranked defe...

[100 rows x 3 columns]

In [82]:
#function that predicts the genre of a singular article

#example sports article
textSports = 'Ryan Day was more than willing to take the win and move on from this one. The way the wind was blowing and rain was falling, it was hard to blame the coach. Miyan Williams ran for 111 yards and two touchdowns, and No. 2 Ohio State overcame the ugly weather and a stiff challenge from Northwestern to win 21-7 on Saturday.'

#example tech article
textTech = 'It has been a while since Instagram introduced a website to let users access the social network from anywhere through a web browser. Over time, Instagram Web has been updated with many new features. This week, the Instagram website has been completely redesigned to take advantage of larger screens.'

def predictArticle(article):

    pred = 0 #prediction value that function returns

    clean_article = cleanArticle(article) #clean the article from extra words and chars
    clean_article = [clean_article] #redeclare article as an iterable object (list)

    cv_article = cv.transform(clean_article) #convert clean article into an array of features

    # print(cv_article)

    temp_NB = naive_bayes.predict(cv_article) #predict the genre of the article

    pred = temp_NB[0] #set value of pred to prediction value from Naive beyes
    # print("prediction: ", pred)

    #returrns 1 if Tech and 0 if Sports

    return pred

predictArticle(textSports)
predictArticle(textTech)

1

In [100]:
from pathlib import Path
import PySimpleGUI as sg

headings = [' Actual Label ', ' Prediction ', '     Article     '] #headers for the table
table = predictedData #actual table

values = table.values.tolist() #value for the table


def popup_text(filename, text): #displays popup whic contains the article the user selected

    layout = [  #declare the layout of the popup window
        [sg.Multiline(text, size=(100, 25)),], #display text on multiple lines instead of one long line, give it size of 100-width and 25-height
    ]
    win = sg.Window(filename, layout, modal=True) #declare window with the name of the file, layout, modal = true means user wont be able to interact with any other windows, 

    while True: #listening to events by using infinite loop
        event, values = win.read() #read events and their values from the window
        if event == sg.WINDOW_CLOSED: #if event of closing the window occues break the loop
            break
    win.close() #close the window

predVal = "Select a file" #predicted value (used later for dispalying article's genre)

sg.theme("DarkTeal2") #declare theme frot the file
layout = [[sg.T("")],
 [sg.Text("Article Sorter")], #text in article sorter
 [sg.Text("---------------------------------------------------------------")],
 [sg.Text(accuracy)],
 [sg.Text(recallScore)],
 [sg.Text(percisionScore)],
 [sg.Table(values = values, headings = headings, #decalre tables where value  is entries converted to list from predictedData and assign headings
 auto_size_columns=False, #default size of columns  = false
 col_widths=list(map(lambda x:len(x)+1, headings)))], #columd width = the size of the heading of that column + 1 for every single row, col_widths must have a value of list
 [sg.Text("---------------------------------------------------------------")],
 [sg.Text("Select an Article: "),
 sg.Input(key="txt"), #declare input witht the id of txt
 sg.FilesBrowse(file_types=(('Text File',' *.txt'),))], #browse through the files display the text files of extension .txt in file browser
 [sg.Button("Submit"),sg.Button("Exit")], #declare button for submit and exit
 [sg.Text("---------------------------------------------------------------")],
 [sg.Text('Prediction: '), sg.Text(predVal, key="-predVal-")]] #declare text which will display predVal(was declared before) and have id of -predVal-


#declare  window
window = sg.Window('Article Sorter', layout, size=(1000,800))

while True: #infinite for loop for listening
    event, values = window.read() #read events and values from the window
    if event == sg.WINDOW_CLOSED or event == 'Exit': #if event with the name of 'Exit'has occured or window has been closed break the loop and close the window
        window.close()
        break
    elif event == 'Submit': #if event witht he name of 'Submit' has occured
        print(values["txt"]) #print value of event 'txt' in the terminal (for debug purposes)
        filename = values['txt'] #assign event value whic will contain the file address to variable called filename
        if Path(filename).is_file(): #if the directory is the file and not folder or anything else
            try: #try block
                with open(filename, "rt", ) as t: #open file with "rt" which means read text
                    text = t.read() #read the text (convert to a string)
                    val_pred = predictArticle(text) #dreturn the prediction value and assignit to a variable
                    # print(val_pred)
                
                if(val_pred == 1): #if prediction value  is 1
                    window['-predVal-'].update("Technology") #update the value of predVal (which is used for displaying the preidction variable on the window) to Technology
                else:
                    window['-predVal-'].update("Sports") #else update to Sports
                    
                popup_text(filename, text) #popup (function defined before) window with the selected text
            except Exception as e: #in case exception happens
                print("Error: ", e) #console log exception

D:/programing/Github Repos/article-sorter/articles/technology/testing/TeTechnologyArticle106.txt